TIMEFRAME = "5m"
EMA_LENGTH = 50
LIQ_LOOKBACK = 10
RR_RATIO = 2.5
SCAN_DELAY = 60

TP_SPLITS = [0.3, 0.3, 0.4]

# OKX USDT PERPETUALS (TOP COINS)
SYMBOLS = [
    "BTC-USDT-SWAP","ETH-USDT-SWAP","SOL-USDT-SWAP","XRP-USDT-SWAP",
    "ADA-USDT-SWAP","AVAX-USDT-SWAP","DOGE-USDT-SWAP","DOT-USDT-SWAP",
    "LINK-USDT-SWAP","TRX-USDT-SWAP","ATOM-USDT-SWAP","LTC-USDT-SWAP",
    "OP-USDT-SWAP","ARB-USDT-SWAP","INJ-USDT-SWAP","APT-USDT-SWAP",
    "NEAR-USDT-SWAP","FIL-USDT-SWAP","SUI-USDT-SWAP"
]
