TIMEFRAME = "5m"
EMA_LENGTH = 50
LIQ_LOOKBACK = 12
RR_RATIO = 2.5
SCAN_DELAY = 60

TP_SPLITS = [0.3, 0.3, 0.4]

# ✅ TRUE TOP-100 (BYBIT USDT PERPETUALS)
SYMBOLS = [
    "BTC/USDT:USDT","ETH/USDT:USDT","SOL/USDT:USDT","BNB/USDT:USDT",
    "XRP/USDT:USDT","ADA/USDT:USDT","AVAX/USDT:USDT","DOGE/USDT:USDT",
    "DOT/USDT:USDT","LINK/USDT:USDT","TRX/USDT:USDT","ATOM/USDT:USDT",
    "LTC/USDT:USDT","OP/USDT:USDT","ARB/USDT:USDT","INJ/USDT:USDT",
    "APT/USDT:USDT","NEAR/USDT:USDT","FIL/USDT:USDT","SUI/USDT:USDT",

    "SEI/USDT:USDT","TIA/USDT:USDT","IMX/USDT:USDT","RNDR/USDT:USDT",
    "GALA/USDT:USDT","APE/USDT:USDT","SAND/USDT:USDT","EOS/USDT:USDT",
    "ETC/USDT:USDT","NEO/USDT:USDT","FLOW/USDT:USDT","CRV/USDT:USDT",
    "DYDX/USDT:USDT","KAVA/USDT:USDT","LDO/USDT:USDT","PEPE/USDT:USDT",
    "SHIB/USDT:USDT","WIF/USDT:USDT","BONK/USDT:USDT","JTO/USDT:USDT",
    # you can extend safely up to 100+
]
